sudo: false
language: node_js
node_js:
- 6
services:
- couchdb
before_install:
- echo "//npm.field.partners/:_authToken=\${NPM_TOKEN}" >> .npmrc
before_script:
- npm install
- ./node_modules/.bin/add-cors-to-couchdb
script:
- npm test
cache:
  directories:
  - node_modules
